Resources:
  LB8A12904C:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes: []
      Scheme: internal
      Subnets:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ","
                - Fn::ImportValue: VPC:TheVPCPrivateSubnetIDsE53B48B1
      Type: network
    Metadata:
      aws:cdk:path: NLB/LB/Resource
  LBapi1listenerAAC7334B:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi1listenerNLBTarget1Group29BF7C7A
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 2000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api1_listener/Resource
  LBapi1listenerNLBTarget1Group29BF7C7A:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 2000
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: ip
      VpcId:
        Fn::ImportValue: VPC:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api1_listener/NLB_Target_1Group/Resource
  LBapi2listener9434057D:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi2listenerNLBTarget2Group98C31D4F
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 3000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api2_listener/Resource
  LBapi2listenerNLBTarget2Group98C31D4F:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: ip
      VpcId:
        Fn::ImportValue: VPC:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api2_listener/NLB_Target_2Group/Resource
  LBapi3listenerC7F2EA36:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi3listenerNLBTarget3Group07F1D5F8
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 4000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api3_listener/Resource
  LBapi3listenerNLBTarget3Group07F1D5F8:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 4000
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: ip
      VpcId:
        Fn::ImportValue: VPC:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api3_listener/NLB_Target_3Group/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.29.0,@aws-cdk/assets=0.28.0,@aws-cdk/assets-docker=0.28.0,@aws-cdk/aws-apigateway=0.28.0,@aws-cdk/aws-applicationautoscaling=0.28.0,@aws-cdk/aws-autoscaling=0.28.0,@aws-cdk/aws-autoscaling-common=0.28.0,@aws-cdk/aws-certificatemanager=0.28.0,@aws-cdk/aws-cloudformation=0.28.0,@aws-cdk/aws-cloudwatch=0.28.0,@aws-cdk/aws-codedeploy-api=0.28.0,@aws-cdk/aws-ec2=0.28.0,@aws-cdk/aws-ecr=0.28.0,@aws-cdk/aws-ecs=0.28.0,@aws-cdk/aws-elasticloadbalancingv2=0.28.0,@aws-cdk/aws-events=0.28.0,@aws-cdk/aws-iam=0.28.0,@aws-cdk/aws-kms=0.28.0,@aws-cdk/aws-lambda=0.28.0,@aws-cdk/aws-logs=0.28.0,@aws-cdk/aws-route53=0.28.0,@aws-cdk/aws-s3=0.28.0,@aws-cdk/aws-s3-notifications=0.28.0,@aws-cdk/aws-servicediscovery=0.28.0,@aws-cdk/aws-sns=0.28.0,@aws-cdk/aws-sqs=0.28.0,@aws-cdk/cdk=0.28.0,@aws-cdk/cx-api=0.28.0,@aws-cdk/region-info=0.28.0,jsii-runtime=node.js/v11.2.0
Outputs:
  LBLoadBalancerArn4723B1BD:
    Value:
      Ref: LB8A12904C
    Export:
      Name: NLB:LBLoadBalancerArn4723B1BD
  ExportsOutputRefLBapi1listenerNLBTarget1Group29BF7C7ABF97B42C:
    Value:
      Ref: LBapi1listenerNLBTarget1Group29BF7C7A
    Export:
      Name: NLB:ExportsOutputRefLBapi1listenerNLBTarget1Group29BF7C7ABF97B42C
  ExportsOutputRefLBapi2listenerNLBTarget2Group98C31D4F01B536BB:
    Value:
      Ref: LBapi2listenerNLBTarget2Group98C31D4F
    Export:
      Name: NLB:ExportsOutputRefLBapi2listenerNLBTarget2Group98C31D4F01B536BB
  ExportsOutputRefLBapi3listenerNLBTarget3Group07F1D5F84B3E76A1:
    Value:
      Ref: LBapi3listenerNLBTarget3Group07F1D5F8
    Export:
      Name: NLB:ExportsOutputRefLBapi3listenerNLBTarget3Group07F1D5F84B3E76A1
